server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8004
  servlet:
    context-path: /

spring:
  profiles:
    include: common
  application:
    name: zxds-mps

  redis:
    database: 7
    host: 192.168.213.137
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  cloud:
    inetutils:
      #子系统注册到Nacos上的IP地址
      preferred-networks: 192.168.213.137

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 300000
