server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8005
  servlet:
    context-path: /

spring:
  profiles:
    #引用application-common.yml文件
    include: common
  application:
    name: zxds-oes
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.213.137:12001/zxds_odr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: abc123456
      initial-size: 4
      max-active: 8
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 6
    host: 192.168.213.137
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  cloud:
    inetutils:
      #子系统注册到Nacos上的IP地址
      preferred-networks: 192.168.213.137

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

# seata 实现分布式事务
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: oes_tx_group
  service:
    vgroup-mapping:
      oes_tx_group: default
  registry:
    type: file
  config:
    type: file

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 300000
