spring:
  profiles: common

tencent:
  cloud:
    appId: 腾讯云APPID
    secretId: 腾讯云SecretId
    secretKey: 腾讯云SecretKey
    region-public: 公有存储桶所在地域
    bucket-public: 公有存储桶名称
    region-private: 私有存储桶所在地域
    bucket-private: 私有存储桶名称

wx:
  app-id: 	wx4c82993ff540bc6e
  app-secret: 666cc866e3ef86b6ebde27ab9399a6b2
  mch-id: 1234567890
  key: 11111111111111111111111111111111
  cert-path: D:\jkweilai\28-zxds\apiclient_cert.p12

minio:
  endpoint: http://192.168.213.317:9000
  access-key: root
  secret-key: abc123456
